language: cpp

os:
- linux

install:
- sudo add-apt-repository -y ppa:beineri/opt-qt521
- sudo apt-get -qy update
- sudo apt-get -qy install qt52base qt52tools

script:
- source /opt/qt52/bin/qt52-env.sh
- lrelease res/lang/en.ts
- qmake apkstudio.pro CONFIG+=release
- make

deploy:
  provider: releases
  api_key:
    secure: IHYkm+WISruGN2YmWoA9qTf2mOry5ean62h3Atymq8zMxIlareEgdviLQKctApkARO0p6B2sht43erzgISCrNJkHNlqqcSd2/VX2cgNhb/hUrtogWNHd3HdpJtN0jHM9rmaoLXhua2WbiTLivpDL3NT+Ai+05Iz/AZ3IOX8anrFG6mjz8HIKhj1L3qAzWPLR3NB69Vk2bZvybN4ggEvhkF6EjD15fPF/fQHgrtr9qZR3YvUt0RN7gC48qgSenPD1LcNqY/TAu5+1ZB2E3PyN9t6gqhLD/HCMr0WVZqvNq0AdaP6UZ3fAjUw7fclVGy/kcuP58qniQqa20ODsGD60vJaEAYktkabVplcXTmKfiqWUAciRVfvZo36ZLW0lkfrUQ4unycipd7stZRuWmJ1IX5ieTWYXjLw9ouchxvpYalSSRHW/6q9+fS2yYbdlzI32lcIX7QYesGTl4u+ofzvGQM1mP1HHU6x2K/fTbNIUnJ3hyVLH53JwfNpKnol5Lv5kO9DA1MetjRfz/ITULZqyyyAct2Ugv0mUfjKwqhWbGlXRmhiXCUvz1wd3Cre+xX7KaXeWxLKM/F3zQOpp2DY3CQccJ28VOj5oql9EwCsp/T8Ns+K4OukHN/GafCN+Rkofc7e4UYUX2IhAz4F76aS1YaW+Bx/xNpm6Z031JW8qpCs=
  file: apkstudio
  on:
    all_branches: true
    repo: brbsix/apkstudio
    tags: true
  overwrite: true
  skip_cleanup: true
